Fix the case when the key is the standard representation of an integer.
yiisoft/cache-memcached pull request #3
Opened 2019-08-21 09:38 UTC by alexkart

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | relates to https://github.com/yiisoft/yii2/issues/17292

2019-08-21 10:16 UTC, samdark requested changes
1. That doesn't seem to test/fix the same thing as described in https://github.com/yiisoft/yii2/issues/17292.
2. That changes behavior from what is specified in PSR-16 to behavior that is not compatible:

```php
@return iterable A list of key => value pairs. Cache keys that do not exist or are stale will have $default as value.
```

2019-08-21 10:45 UTC, alexkart commented
> 1. That doesn't seem to test/fix the same thing as described in [yiisoft/yii2#17292](https://github.com/yiisoft/yii2/issues/17292).
> 2. That changes behavior from what is specified in PSR-16 to behavior that is not compatible:
> 
> ```
> @return iterable A list of key => value pairs. Cache keys that do not exist or are stale will have $default as value.
> ```

1. It's related to the same issue converting string `'111'` to integer `111` by the `foreach` and `array_merge`
2. What's the change? The behavior after the change is the same.

2019-08-21 11:39 UTC, alexkart commented
I'm also thinking of adding a key validation method, as `$key` variables in all interface methods are not type hinted and you can pass a key which is not a string to the `set` method for example. You will still get `TypeError` in this case but per the interface, it should throw `InvalidArgumentException`.

2019-08-21 20:01 UTC, samdark commented on src/Memcached.php
> +        $values = array_fill_keys($this->iterableToArray($keys), $default);
How about:

```php
$defaultValues = array_fill_keys($this->iterableToArray($keys), $default);
foreach ($defaultValues as $key => $value) {
    yield $key => $valuesFromCache[$key] ?? $value;
}
```

2019-08-21 20:01 UTC, samdark commented on src/Memcached.php
> +    private function validateKey($key, $multiple = false, $withValues = false): void
Worth having multiple methods instead of one with boolean switches.

2019-08-21 20:02 UTC, samdark commented
OK I was confused by variable naming. Change is OK.

2019-08-22 08:48 UTC, alexkart commented on src/Memcached.php
> +        $values = array_fill_keys($this->iterableToArray($keys), $default);
Do you mean returning a generator from `getMultiple` instead of an array? Why do you think it's better?

2019-08-22 09:05 UTC, samdark commented on src/Memcached.php
> +    private function validateKeys($keys): void
```suggestion
    private function validateKeys(iterable $keys): void
```

2019-08-22 09:05 UTC, samdark commented on src/Memcached.php
> +    private function validateKeysOfValues($values): void
```suggestion
    private function validateKeysOfValues(array $values): void
```

2019-08-22 09:07 UTC, samdark commented on src/Memcached.php
> +        $values = array_fill_keys($this->iterableToArray($keys), $default);
Yes. I mean generator.

1. The return type does not require array.
2. You can have less confusing variable names.

But overall, current variant is fine as well.

2019-08-22 09:08 UTC, samdark approved these changes

2019-08-22 09:13 UTC, alexkart commented on src/Memcached.php
> +        $values = array_fill_keys($this->iterableToArray($keys), $default);
So, let's leave the current version? As for me, an array is more convenient and easier to test.

2019-08-22 09:38 UTC, samdark commented on src/Memcached.php
> +        $values = array_fill_keys($this->iterableToArray($keys), $default);
Yes. It's fine.

2019-08-22 09:39 UTC, merged

2019-08-22 09:39 UTC, samdark commented
Merged. Thank you very much!